### ISSUE TITLE
`ctag` support (f/k/a “Hey Dustin, you are the best”)

### ISSUE THREAD

**Issue by vlrevolution** [spdustin/ChatGPT-AutoExpert#1]
Great work on this cutting edge prompt engineering spectacle.

I am beyond impressed.

What is the purpose of the /ctags for the developer version? What are you using it for. Does the dev version actually utilize the ctags after they have been created or it is only meant for the user. Just making sure I understand this

Keep up the good work. I'm testing as we speak

**Comment by spdustin** [comment]
Thanks!

I currently use the `ctags` functionality by reminding ChatGPT that it's there when I'm editing code that's split across multiple files.

For example, I'll say something like:

> The WLED usermod we're building doesn't seem like it's creating segments properly. Check the ctags to see where the segment creation logic is, and adjust the usermod to use the correct signature when creating a new segment.

I'm working on another update that will use a Python package to read ctags in a more Pythonic way, but currently, ChatGPT will just read the tags and filter them with a regex to find which file has a function it's looking for.

**Comment by vlrevolution** [comment]
That's a clever idea. Thanks for sharing

**Comment by spdustin** [comment]
Holding this issue open to track that enhancement.

**Comment by spdustin** [comment]
Just adding an update here: I got waylaid by a Jupyter-enhanced version of the Standard Edition, but I am getting back to the Developer Edition side this week.

I already have a little progress on more native ctags-“light” support,]. I’m hoping to avoid users having to upload a wheel (or the ctags zip) when they init each session.

**Comment by SeaDude** [comment]
Is my understanding correct that `ctags` are being used as a sort of static, file-based memory?

**Comment by spdustin** [comment]
> Is my understanding correct that `ctags` are being used as a sort of static, file-based memory?

Yes, that’s right. But I’m moving away from it, and the next version will bundle `tree-sitter` with pre-compiled languages ready to go.

Just finished a trial run, in fact, against the released autodev.py companion:

|   Start row number |   End row number | Function name               | Parameters                  |
|-------------------:|-----------------:|:----------------------------|:----------------------------|
|                 57 |               70 | help                        | ()                          |
|                 73 |              103 | stash                       | ()                          |
|                106 |              117 | recall                      | ()                          |
|                120 |              137 | ctags                       | ()                          |
|                140 |              154 | install_ctags               | ()                          |
|                157 |              195 | memory                      | ()                          |
|                198 |              205 | _get_methods_and_docstrings | (cls)                       |
|                208 |              220 | _slash_command              | (command: str)              |
|                223 |              256 | _get_simple_ctag_tree       | ()                          |
|                260 |              278 | _install_ctags              | (archive_path: str)         |
|                282 |              365 | _setup                      | (character_choice: int = 0) |

**Comment by spdustin** [comment]
The idea is then to instruct ChatGPT to call a new function `get_symbol_tree(filepath: str)` in the autodev companion module (which will be a wheel, so it’ll just import it into Jupyter) whenever it needs info about code it’s editing, allowing it to more easily edit individual symbols with precision, and create diffs to preserve a history of changes to sandbox files.

**Comment by SeaDude** [comment]
Thank you for the explanation. I'm also curious what role Jupyter is playing. Is ChatGPT using Jupyter behind the web app?

**Comment by spdustin** [comment]
Yes, it is. All the code cells executed in the sandbox are run in a Jupyter kernel. The `/memory` slash command exports the Jupyter notebook “under” the chat, and includes it in the archive.
