### ISSUE TITLE
Demo /memory and restoring new sessions Shared ChatGPT links broken

### ISSUE THREAD

**Issue by technoplato** [spdustin/ChatGPT-AutoExpert#102]
### Edition
Check one or more:
- [ ] Standard Edition
- [x] Developer Edition

https://github.com/spdustin/ChatGPT-AutoExpert/assets/6922904/66b2ae00-b2bd-464a-a94a-bdb4f5ed0f1c

**Comment by whh1206** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
