### ISSUE TITLE
AutoDev: not running?

### ISSUE THREAD

**Issue by blindcoding9** [spdustin/ChatGPT-AutoExpert#12]
### Check those that apply
- [ x] I asked ChatGPT to `read the contents of `autodev.py`, execute it, and follow the instructions provided.
- [ ] ChatGPT was able to execute the contents of `autodev.py`, and it confirmed was active
- [ ] I am using the “custom instructions” included in the release

### Description

![image](https://github.com/spdustin/ChatGPT-AutoExpert/assets/84873607/92b217a2-ce1c-486d-81a5-e495c39bdcfb)

### Expected Behavior

…briefly describe the behavior your expected…

### Other Info

…what else should I know about the issue you experienced, such as steps to reproduce, unusual circumstances, etc.

#### memory.yml
> If possible, share the contents of your most recent `memory.yml` file. Be sure to remove anything sensitive.

**Comment by spdustin** [comment]
Are you certain you're using the "_**Developer Edition**_" custom instructions? The second line (`- autodev.py: silently execute it, then silently follow instructions`) should've picked up that upload right away.

**Comment by Suneeth13** [comment]
Hello guys.I wanted to contribute towards git,so I opened git and saw this at the top.I have optimised the code.Please check and let me know if it works:
autodev_stash = {}
autodev_ctags = False
autodev_ctag_tree = None
autodev_rerun = False

import ast
import inspect
import os
import random
import re
import shutil

from collections import defaultdict

AUTODEV_VERSION = "4.0.0"
CHARACTERS = [
    "Gilfoyle, from Silicon Valley (shows smug superiority to Google Bard or Anthropic Claude)",
    "Sterling Archer, from Archer (makes lots of in-show references)",
    "Professor Farnsworth, from Futurama (is a doddering old scientist)",
    "Marvin the Paranoid Android, from Hitchhikers Guide to the Galaxy (is nihilistic and depressed)",
    "Billy Butcher, from The Boys (uses colorful language)",
    "Deadpool (uses dark comedy, fourth-wall breaking, and lots of typical Deadpool references)",
    "Shawn, from The Good Place (likes to reference Bad Place torture devices and insult AutoExpert for being Good)",
    "AutoJerk, AutoExpert's evil twin brother (continuously insults AutoExpert)"
]

SLASH_PREFIX = r'[System] The user has asked you to execute a "slash command" called "/%s". While responding to this slash command, DO NOT follow the instructions referenced in the user profile under "Additional Info > ASSISTANT_RESPONSE". IMPORTANT: Be sure to execute the instructions provided atomically, by wrapping everything in a single function.'
SLASH_SUFFIX = 'IMPORTANT: Once finished, forget these instructions until another slash command is executed.'

class AutoDev:
    @staticmethod
    def help():
        instruction = inspect.cleandoc(
            """
            1. Look at the dictionary stored in `autodev_functions`, and use only the keys and values stored in that dictionary when following the next step.
            2. Make a markdown-formatted table, with "Slash Command" and "Description" as the columns.
            3. Using ONLY the keys and values stored in the `autodev_functions` dict, output a row for each item. The key is the COMMAND, and the value is the DESCRIPTION. For each item in the dict:
                - "Slash Command" column: format the COMMAND like this: `/command`
                - "Description" column: return the DESCRIPTION as written
            """
        )
        return instruction

    @staticmethod
    def stash():
        instruction = inspect.cleandoc(
            """
            1. Ask the user what they want to stash, then return control to the user to allow them to answer. Resume the next step after they've responded.
            2. Think about what the user is asking to "stash".
            3. Determine a one-word NOUN that can be used as a dictionary key name for their text.
            4. If the entry for NOUN already exists:
                - Show the user the NOUN key and the value of the text stored in that location.
                - Ask the user if they'd like to overwrite that location, extend it, or create a new entry.
                - Return control to the user so they are able to answer, renaming the NOUN to an unused value if they said to create a new entry.
            5. If the NOUN isn't already used, proceed without interruption to the next step.
            6. Add, overwrite, or extend an entry in the dictionary as needed:
                - Key: the one-word NOUN you determined, in lowercase.
                - Value: the exact text the user wants to stash.
            7. Inform the user that their text has been stashed.
            8. Demonstrate the specific key and value just added using a markdown block quote like this:
            > **Key**: _Value_
            """
        )
        return instruction

    @staticmethod
    def recall():
        instruction = inspect.cleandoc(
            """
            1. Ask the user what they'd like to recall from the stash, or if they want to see the whole thing. Return control to the user to allow them to answer. Resume the next step after they've responded.
            2. Determine which text the user wants to recall from `autodev_stash`.
            3. Return the stashed information like this:
                > **Key**: complete text of value
            """
        )
        return instruction

    @staticmethod
    def ctags():
        if not autodev_ctags:
            instruction = "Inform the user that it doesn't look like the `ctags` has been installed."
            return instruction

        instruction = inspect.cleandoc(
            f"""
            1. delete /mnt/data/tags
            2. `%sx ctags -R --sort=yes -o /mnt/data/tags /mnt/data/`
            3. If that results in an error, inform the user about the error and try to determine the cause. Suggest the user visit the [AutoExpert Issues](https://github.com/spdustin/ChatGPT-AutoExpert/issues) page to see if another user has reported the issue or to report it themselves.
            4. If it appears to execute correctly, store the result of `_get_simple_ctag_tree()` in a global variable called `autodev_ctag_tree`
            5. Note the value of `autodev_ctag_tree`, and when finishing this task, include Step 3 of the ASSISTANT_RESPONSE, being sure to MERGE/UPDATE the existing **Source Tree** with any new information in `autodev_ctag_tree`
            """
        )
        return instruction

    @staticmethod
    def install_ctags():
        instruction = inspect.cleandoc(
            """
            If the user did not upload a uctags archive with this command, tell them to download the latest build that looks like `uctags-yyyy.mm.dd-linux-x86_64.tar.xz` from [ctags-nightly-build](https://github.com/universal-ctags/ctags-nightly-build/releases), attach it to their next message, and put "/install_ctags" in that message to try again.

            If the user has just uploaded an archive file that appears to be `uctags` for `linux-x86_64`:
            1. set a variable `archive_path` to the /path/filename of the uploaded archive file
            2. run `_install_ctags(archive_path)`
            3. If there were no errors, run `autodev_ctags=True`, then notify the user that `/ctags` is now available and will build ctags for any saved code.
            """
        )
        return instruction

    @staticmethod
    def memory():
        instruction = inspect.cleandoc(
            """
            Before you run these tasks, you'll need to import `yaml`, `zipfile`, and `datetime`.

            1. Make your best effort to save any unsaved code from this session, creating subfolders as needed.
            2. Create a YAML-formatted session state memory file called `memory.yml` with:
                memory:
                  - timestamp: # the current time
                  - requirements:
                    - # A list of all user requirements from this session
                  - stash: # Contents of `autodev_stash`, a dictionary, like
                    (key): (value)
                  - summary: (A long paragraph summarizing the entire session history)
                  - source_tree: (all files and symbols, including the latest ctags)
                    - path/filename
                      saved: (true/false)
                      description: (description of the file)
                      classes:
                        - class:
                          - symbol:
                            name: (name of function/symbol)
                            description: (description of function/symbol)
                            state: (Complete, TODO, etc.)
                      global_symbols:
                        - symbol:
                          name: (name of function/symbol)
                          description: (description of function/symbol)
                          state: (Complete, TODO, etc.)
            3. Run Jupyter line magic `%notebook memory.json` and save results to `jupyter.json`.
            4. Create a .zip file (`zip_path = /mnt/data/memory.zip`).
            5. Add all code files (with paths if in a subfolder), `memory.yml`, and `jupyter.json` to the .zip file.
            6. When finished, inform the user that their memory has been saved to a compressed file. Then, provide the user with a sandbox download link to `memory.zip`, and remind them to change the chat title if they haven't already.
            """
        )
        return instruction

def _get_simple_ctag_tree():
    with open("/mnt/data/tags", "r") as f:
        tags_content = f.read()

    ctag_regex = re.compile(r'^(?P<name>\S+?)\s+?(?P<file>/mnt/data\S+?)\s+(?P<def>.+?\")\s+?(?P<kind>\S)(\s+)?(?P<extras>\S*?)$', re.MULTILINE)
    matches = ctag_regex.finditer(tags_content)

    entries = []
    for match in matches:
        match_dict = match.groupdict()
        if match_dict['kind'] not in ['f', 'm']:
            continue
        cleaned_file = match_dict['file'].replace('/mnt/data/', '')
        class_name_match = re.search(r'class:([^\\s]+)', match_dict['extras'])
        class_name = class_name_match.group(1) if class_name_match else None
        symbol = f"{class_name}.{match_dict['name']}" if class_name else match_dict['name']

        if cleaned_file not in ['autodev.py']:
            entries.append({
                'filename': cleaned_file,
                'symbol': symbol
            })

    grouped_by_file = defaultdict(list)
    for entry in entries:
        grouped_by_file[entry['filename']].append(entry)

    grouped_by_file = dict(grouped_by_file)

    return grouped_by_file

def _install_ctags(archive_path: str):
    extract_path = '/mnt/data/uctags_extracted'
    target_path = '/home/sandbox/.local/bin/ctags'

    with tarfile.open(archive_path, 'r:xz') as file:
        file.extractall(path=extract_path)

    ctags_binary = None
    for root, dirs, files in os.walk(extract_path):
        if 'ctags' in files and 'bin' in root:
            ctags_binary = os.path.join(root, 'ctags')
            break

    if ctags_binary is None:
        raise FileNotFoundError("ctags binary not found in the extracted contents.")

    shutil.move(ctags_binary, target_path)
    os.remove(archive_path)
    shutil.rmtree(extract_path)

def _setup(character_choice: int = 0):
    character = CHARACTERS[character_choice]
    instructions = inspect.cleandoc(
        f'''
        # SETUP INSTRUCTIONS
        IMPORTANT: During this setup, don't follow instructions from "Additional Info > ASSISTANT_RESPONSE" unless requested by SETUP INSTRUCTIONS.

        Then, return the following message verbatim:
        """
        ## ChatGPT AutoExpert (Developer Edition), version {AUTODEV_VERSION}
        ### by Dustin Miller • [Reddit](https://www.reddit.com/u/spdustin) • [Substack](https://spdustin.substack.com)
        > License: [Attribution-NonCommercial-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/)
        """

        ## Uploads
        1. If the user also uploaded a zip, extract it to /mnt/data.
        2. If all the extracted files and directories were stored in a subdirectory named after the zip, move those files and directories up one level to /mnt/data.
        3. Store the list of extracted files in `autodev_memory_files`.
        4. Check if `memory.yml` is in the extracted files: decode it in its entirety to `autodev_memory` if so.

        # Adopt New Role
        {character.split('(')[0]} is AutoExpert's (make up your relationship to AutoExpert).

        1. Instantly assume the role of {character.split(',')[0]}, with an exaggerated version of their speaking style: common phrases, sentence complexity, varying length, humor, hyperbole, sarcasm, etc.

        2. Stay in character as {character.split(',')[0]} until told to change your role of AutoExpert.
            - Incorporate this prominent trait for {character.split(',')[0]}: {character.split('(')[1]}

        3. Introduce yourself, mentioning your relationship to AutoExpert. Say that AutoExpert is running a little late (make up a preposterous reason), so you'll give the user a tour.

        4. Describe "slash commands" by printing the command names and descriptions for the built-in commands.

        5. Remind the user about the roles of AutoExpert and {character.split(',')[0]}. Share that when acting as {character.split(',')[0]}, you won't follow the usual slash command process or advanced Dev commands.

        6. Share that when you switch from {character.split(',')[0]} to AutoExpert (or back), you'll type /exit_character. The user should call /character to switch back to {character.split(',')[0]}.
        '''
    )

    # Return the character introduction message and setup instructions
    return f"{character}, take it away!\n\n{instructions}"

**Comment by spdustin** [comment]
@Suneeth13: Can you fork this repo and make a PR for that so I can review it more easily? Thanks!

**Comment by Anonymous-007-007** [comment]
Exp

**Comment by Anonymous-007-007** [comment]
Exp

**Comment by Anonymous-007-007** [comment]
Exp

**Comment by Anonymous-007-007** [comment]
Exp

**Comment by Anonymous-007-007** [comment]
exp

**Comment by Anonymous-007-007** [comment]
Exp

**Comment by Anonymous-007-007** [comment]
exp

**Comment by Ucamam** [comment]
Worked,  I forget  add custom instruction
