### ISSUE TITLE
AutoDev: Verbosity changes on its own

### ISSUE THREAD

**Issue by schind87** [spdustin/ChatGPT-AutoExpert#15]
### Check those that apply
- [x] I asked ChatGPT to `read the contents of `autodev.py`, execute it, and follow the instructions provided.
- [x] ChatGPT was able to execute the contents of `autodev.py`, and it confirmed was active
- [X] I am using the “custom instructions” included in the release

### Description

After about 4 responses, AutoExpert changed its verbosity to V=1:

**Language > Specialist**: AutoIt > GUI Automation Expert  
**Includes**: AutoIt core libraries  
**Requirements**: Verbosity level is set to V=1 for concise code. The focus is on debugging, performance, and logging enhancements.  

### Expected Behavior

I would expect it to stay at the default of V=2

### Other Info

I just gave it autodev.py as first prompt and didnt give it instructions or have it explicitly confirm it was active.

**Comment by spdustin** [comment]
Can you share the exact text of the request prior to that verbosity change?

**Comment by isspid** [comment]
Same thing happened to me. Here is my prompt: `Explain to me ctags with examples: Code snippets and input output, also real life scenarios`

**Comment by spdustin** [comment]
A couple things:
* In **Developer Edition**, the `VERBOSITY` is intended to apply only to code written by GPT. I didn’t evaluate its effect on prose.
* The `VERBOSITY` effect on non-code responses is therefore unverified by testing, but anecdotally, it should not affect the non-code of its responses either way. It’s personality (the experts it assigned) is the only thing that can impact the non-code prose it writes.
* It `VERBOSITY` is not specified when asked for code, it’ll infer a value based on phrasing of the request; it usually defaults to `V=2 simple`, but it might presume you need `V=3 verbose, DRY with extracted functions` with complex code requests
* It normally keeps the verbosity setting for a given file being edited until overridden

**Comment by schind87** [comment]
> Can you share the exact text of the request prior to that verbosity change?

I cant find that part of the conversation anymore, sorry!

**Comment by spdustin** [comment]
No worries. I'm going to mark this as closed for a couple reasons:

1. An earlier comment describes how it uses `VERBOSITY`
2. A forthcoming update changes those instructions around a bit for folks that are _primarily_ chatting about code, rather than primarily _writing_ code.
