### ISSUE TITLE
Tables and Graphs

### ISSUE THREAD

**Issue by Marino252525** [spdustin/ChatGPT-AutoExpert#35]
### Edition
Check one or more:
- [x] Standard Edition
- [ ] Developer Edition

Hello Dustin,

I am writing to follow up on the discussion we had on Reddit concerning automated data visualization and tabular data presentation features. I have made some updates to the 'About Me' section of your Standard Edition Custom Instructions. Below are the changes I've implemented:

# Data Visualization
- **Use matplotlib.pyplot for graphical data visualization whenever the data is better represented visually. This is the default setting for all data-related queries unless specified otherwise.**
- **Present tabular data using Markdown tables**

While the changes are operational, I would greatly appreciate your expertise in assessing their efficiency, particularly in terms of token usage. As I strive for optimal performance, your insights on this matter would be invaluable.

Thank you for your continued support; it truly makes a difference.

Best regards,

Marino

**Comment by spdustin** [comment]
Heya, Marino!

Right now, my current WIP for v6 of Standard Edition has this instruction:

```markdown
- Visualize all data with Markdown tables (text) or Seaborn (visual and EDA)
```

I think it does a pretty good job attending to that. EDA is a common abbreviation in data science/engineering; `EDA` is even its own token. To evaluate, I dropped [this dataset](https://data.world/makeovermonday/2023w36) into a chat with ADA and asked is simply “What can you show me about this data?”

After scanning through the files in the archive, it first summarized the stats like this:

***

### Exploratory Data Analysis (EDA) Summary

#### Basic Statistics

| Statistic           | year     | forbes_rank | current_employees | valuation_billions |
|---------------------|----------|-------------|-------------------|--------------------|
| Count               | 200      | 200         | 200               | 196                |
| Mean                | 2022.5   | 50.5        | 1358.93           | 7.11               |
| Standard Deviation  | 0.50     | 28.94       | 1287.92           | 9.82               |
| Min                 | 2022     | 1           | 44                | 0.61               |
| 25th Percentile (Q1)| 2022     | 25.75       | 630               | 3                  |
| Median (Q2 / 50th)  | 2022.5   | 50.5        | 1000              | 4.45               |
| 75th Percentile (Q3)| 2023     | 75.25       | 1748.5            | 7.5                |
| Max                 | 2023     | 100         | 9300              | 95                 |

#### Missing Values

- `valuation_billions`: 4 missing values

#### Observations

1. The dataset contains 200 records, likely 100 for each year (2022 and 2023).
2. The `forbes_rank` ranges from 1 to 100, as expected for a ranking list.
3. The `current_employees` varies widely, from as few as 44 to as many as 9300.
4. The `valuation_billions` also has a wide range, with a minimum valuation of 0.61 billion and a maximum of 95 billion dollars.
5. There are 4 missing values in the `valuation_billions` column, which may need attention.

***

After asking if I wanted to address missing data or perform a deeper analysis, I said “deeper analysis”, and it returned this first Seaborn multi-plot and commentary:

![IMG_0328](https://github.com/spdustin/ChatGPT-AutoExpert/assets/1342542/9ca1c967-7cf4-4762-8e98-bd2ad284f67d)

### Deeper Analysis: Data Visualizations

#### 1. Distribution of Current Employees
- The distribution is right-skewed, indicating that most companies have fewer employees, with a few outliers having a very high number of employees.

#### 2. Distribution of Valuation (in billions)
- The valuation distribution is also right-skewed. Most companies are valued between 0 and 20 billion dollars, with fewer companies having extremely high valuations.

#### 3. Current Employees by Year
- The boxplot indicates that the distribution of employees is similar across both years, 2022 and 2023. There are some outliers in both years.

#### 4. Valuation by Year
- The valuation seems to be fairly consistent between the two years, with some outliers present in both.

### Key Takeaways

- Both the number of employees and the valuation are right-skewed, indicating the presence of a few companies that are significantly larger or more valuable than the rest.
- There doesn't appear to be a drastic change in either the number of employees or valuation from 2022 to 2023 based on the boxplots.

⏯️ Would you like to explore any specific aspect further, such as companies with the highest growth, outliers, or any other dimension?

***

I said “EDA, whether or not they had layoffs”, and it replied:

![IMG_0327](https://github.com/spdustin/ChatGPT-AutoExpert/assets/1342542/af6c0e77-cead-4917-b931-7e0b3042ae5a)

### EDA Focused on Layoffs

#### 1. Distribution of Current Employees by Layoffs
- Companies that had layoffs generally have a wider range of employee counts, but they also include some of the companies with the highest numbers of employees.
- Companies without layoffs mostly cluster in the lower range of employee counts.

#### 2. Distribution of Valuation (in billions) by Layoffs
- Companies that had layoffs seem to have a broader valuation range compared to those that did not. 
- Companies without layoffs appear to be more concentrated in the lower valuation range.

#### 3. Current Employees by Year and Layoffs
- In both years, companies that had layoffs seem to have a wider interquartile range of employee counts.
- Companies that did not have layoffs tend to have fewer employees, especially in the year 2022.

#### 4. Valuation by Year and Layoffs
- The valuation of companies that had layoffs is generally higher in both years compared to those without layoffs.
- There are outliers in both categories, indicating extremely high valuations irrespective of layoffs.

### Key Takeaways

- Layoffs appear to be more common among companies with higher valuations and larger employee counts.
- The data suggests that having a high valuation or a large number of employees does not necessarily protect a company from layoffs.

***

**Comment by Marino252525** [comment]
That worked perfectly! 

I used another data set and it did the tables and graphics automatically!

Thank you so much Dustin!!!

**Comment by spdustin** [comment]
Great, glad to hear. Cheers!
