### ISSUE TITLE
capture the coupon payment dates

### ISSUE THREAD

**Issue by JennyL3** [spdustin/ChatGPT-AutoExpert#49]
### Edition
Check one or more:
- [x] Standard Edition
- [ ] Developer Edition

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JennyL3** [comment]
can you capture the dates from pdf

**Comment by spdustin** [comment]
If you have a paid ChatGPT subscription, you can use the “Advanced Data Analysis” mode of GPT-4, which can often read information from PDF files. There are so many ways for tools to _create_ the PDF files, so there’s no way to predict if GPT-4 with Advanced Data Access can read it.

Alternately—and you still need a paid ChatGPT sub for this—you can upload a _screenshot_ of the PDF and it can often extract info from it.

At any rate, AutoExpert doesn’t help or hurt in this case—it’s all up to GPT-4 to do that work. Good luck!
