### ISSUE TITLE
AutoDev: 

### ISSUE THREAD

**Issue by ataxy** [spdustin/ChatGPT-AutoExpert#56]
### Check those that apply
- [ x] I asked ChatGPT to `read the contents of `autodev.py`, execute it, and follow the instructions provided.
- [x ] ChatGPT was able to execute the contents of `autodev.py`, and it confirmed was active
- [x ] I am using the “custom instructions” included in the release

### Description

/memory does not work

### Expected Behavior

get a zip file

### Other Info

response given by chatgpt:

I don't have the capability to remember past interactions or store any kind of memory for future reference. Each interaction with me is stateless, meaning I don't have a history of past conversations. If you have a specific question or need help with a particular topic, feel free to ask!

#### memory.yml
> If possible, share the contents of your most recent `memory.yml` file. Be sure to remove anything sensitive.

**Comment by ataxy** [comment]
thx for the help and support, i finally had to add ctag to the folder where autodev.py is, it works fine now, so far, this project is quite usefull

**Comment by spdustin** [comment]
Thanks! Upcoming update uses `treesitter`, and is much more capable, stay tuned!
