### ISSUE TITLE
AutoDev:

### ISSUE THREAD

**Issue by IAlready8** [spdustin/ChatGPT-AutoExpert#57]
### Check those that apply
- [x] I asked ChatGPT to `read the contents of `autodev.py`, execute it, and follow the instructions provided.
- [ ] ChatGPT was able to execute the contents of `autodev.py`, and it confirmed was active
- [x] I am using the “custom instructions” included in the release

### Description

…briefly describe what went wrong…

### Expected Behavior

…briefly describe the behavior your expected…

### Other Info

…what else should I know about the issue you experienced, such as steps to reproduce, unusual circumstances, etc.

#### memory.yml
> If possible, share the contents of your most recent `memory.yml` file. Be sure to remove anything sensitive.

**Comment by spdustin** [comment]
Closed as empty
