### ISSUE TITLE
ChatGPT reads preamble out loud in voice conversations 

### ISSUE THREAD

**Issue by ba32107** [spdustin/ChatGPT-AutoExpert#58]
### Edition
Check one or more:
- [x] Standard Edition
- [ ] Developer Edition

When using the voice conversation feature from the app, ChatGPT will read out loud the preamble, including all the keywords which sometimes can be quite long. It also (naturally) won't be able to follow or open links, but instead says "Please open the app to see this link" which can be quite annoying. 

Suggestion: when in voice conversation mode, AutoExpert should ask ChatGPT to not read the preamble and omit the "see also" sections (and everything with links), and just generally make the voice experience a bit better.

If that's not possible, I'd prefer to turn off AutoExpert completely in voice mode - is it possible?

**Comment by spdustin** [comment]
Try [these instructions](https://github.com/spdustin/ChatGPT-AutoExpert/tree/dev__voice_edition/voice-edition) (still under development) for voice conversation mode:

**Comment by ba32107** [comment]
Very cool, thanks. This seems like it's gonna be super useful for voice convo. However, it's not quite what I'm looking for.

What I'm after is to keep the existing format of AutoExpert when using written conversation, but behave differently when we are in voice mode. I made a fork and customized the instructions a little bit:
https://github.com/ba32107/ChatGPT-AutoExpert/pull/1/files

I don't really like the hyperlinks, so I removed those, but for the purposes of this issue, the interesting bit is Step 0 that I added. I'm looking for something like that. This does not work (it still reads out the preamble), and I can kinda guess why, but I'm wondering if there is a way to make it work?

Once your voice instructions are ready to release, I think it'd be awesome to somehow combine them with the regular instructions, so I can use voice and text mode seamlessly! I realize this is challenging with the custom instruction character limits though.

**Comment by spdustin** [comment]
I’ll explore more options for determining if it’s a voice conversation, and changing the way it generates its completions. ChatGPT didn’t distinguish between text or voice **output**, but it does for **input** as a new system message is injected when you’re in a voice conversation.

**Comment by ba32107** [comment]
Yep, I know that part - that's how my IF statement can work. 

To clarify, my only problem with the current instructions is that the preamble table is read out with voice mode - and sometimes it takes 30 seconds or so. If that can be fixed in any way (such that I don't need _separate_ custom instructions for voice mode) that would be excellent!

Thanks for your hard work on this.

**Comment by spdustin** [comment]
I have a TamperMonkey UserScript hiding at the root of the repo that makes toggling a bit easier. You can point it to your own versions on GitHub Gists or you've made changes.
