### ISSUE TITLE
Perplexity Compatible Prompts and Instructions

### ISSUE THREAD

**Issue by nviraj** [spdustin/ChatGPT-AutoExpert#66]
### Edition
Check one or more:
- [x] Standard Edition
- [x] Developer Edition

Hi Dustin, thanks for your work on this and the willingness to share. 
I remember seeing on [Reddit](https://www.reddit.com/r/OpenAI/comments/173cwgs/autoexpert_v5_custom_instructions_by_spdustin/k5ekb4b/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button), that you might release instructions and prompts compatible with perplexity as well.

Would love to have this. Some info that might be of interest:

- Claude 2 and GPT4 exists for Pro. 
- Perplexity Model is available for free, which is probably GPT 3.5 (Used to be definitely GPT3.5, but there are some indications that a Llama 2 variant is being used as well)
- AI Profile exists ( (~1500 characters)
- Collections have their own set of profiles which overrides AI profile (~1000 characters)

Thank you!

**Comment by spdustin** [comment]
I have a working set for Claude 2 on Poe now, I could probably post a version for Perplexity's Claude also... I'll leave this open and add to my roadmap.

**Comment by spdustin** [comment]
Bumping, it's been crazy here... I'll get to this soon!

**Comment by nviraj** [comment]
Absolutely no worries Dustin! 
Thanks for retaining this in your roadmap. Perplexity now uses the updated Claude 2.1 FYI.
