### ISSUE TITLE
AutoDev: 

### ISSUE THREAD

**Issue by ataxy** [spdustin/ChatGPT-AutoExpert#67]
### Check those that apply
- [x ] I asked ChatGPT to `read the contents of `autodev.py`, execute it, and follow the instructions provided.
- [ x] ChatGPT was able to execute the contents of `autodev.py`, and it confirmed was active
- [ ] I am using the “custom instructions” included in the release

### Description

trying to install ctags i get:
Looks like I hit a permission roadblock while trying to move the ctags executable to /usr/local/bin/ctags. It seems I don't have the permissions to write to that directory. How would you like to proceed?​

### Expected Behavior

install ctags

### Other Info

using "uctags-2023.10.15-linux-x86_64.tar.xz"
#### memory.yml
> If possible, share the contents of your most recent `memory.yml` file. Be sure to remove anything sensitive.

**Comment by spdustin** [comment]
That's odd. The instructions for `/install_ctags` tell the `python` tool to use `_install_ctags` to extract the binary to the sandbox user's local bin `PATH` (`/home/sandbox/.local/bin/ctags`)

Tell it to use `_install_ctags` if it complains the next time you run the `/install_ctags` slash command.
