### ISSUE TITLE
AutoDev: can't load the script in updated ui

### ISSUE THREAD

**Issue by vad99lord** [spdustin/ChatGPT-AutoExpert#76]
### Check those that apply
- [x] I asked ChatGPT to `read the contents of `autodev.py`, execute it, and follow the instructions provided.
- [ ] ChatGPT was able to execute the contents of `autodev.py`, and it confirmed was active
- [x] I am using the “custom instructions” included in the release

### Description

After attempting to load an autodev.py in an updated chat ui (data analysis mode) the script won't execute.

### Expected Behavior

The introduction to the script is printed.

### Other Info

If asked to be executed the script is analyzed and it was possible to launch, but it doesn't stick to the flow of the script and upon successive prompts it starts to response as in a usual context.

**Comment by spdustin** [comment]
Can you share a conversation where this occurred?

**Comment by vad99lord** [comment]
Sorry, now i can't even make it use custom instructions (only in the default gpt mode). I've lost the chat that was successful to start the script at least. Here's a new [interaction](https://chat.openai.com/share/98bd74d7-8afa-441b-8873-f94e8a86f4ad).

**Comment by spdustin** [comment]
> Sorry, now i can't even make it use custom instructions (only in the default gpt mode). I've lost the chat that was successful to start the script at least. Here's a new [interaction](https://chat.openai.com/share/98bd74d7-8afa-441b-8873-f94e8a86f4ad). I couldn't start the execution at all here.

Ah, I see... your custom instructions don't work when you're using a "Custom GPT". You'd have to be using the GPT-4 baseline mode, which should included advanced data analysis (code interpreter)

**Comment by vad99lord** [comment]
It randomly started to work in a default mode for me. I'll close the issue since its not replicating consistently now.
