### ISSUE TITLE
Encourage responses in the language in which the question is asked

### ISSUE THREAD

**Issue by zzhang1** [spdustin/ChatGPT-AutoExpert#79]
### Edition
Check one or more:
- [x] Standard Edition
- [ ] Developer Edition

**Is your feature request related to a problem? Please describe.**
Given the patterns in the prompt are in English, GPT tends to respond to questions asked in any language using English only.

**Describe the solution you'd like**
Adding one sentence into the instructions to respond in the language that the user provided input seems to solve the issue. The patterns are then translated into that language, and the results seem mostly just as effective.

**Comment by spdustin** [comment]
This has been done for the "Chat" version of the CustomGPT, and will be in the next AutoExpert custom instructions.
