### ISSUE TITLE
userscript feedback

### ISSUE THREAD

**Issue by panckreous** [spdustin/ChatGPT-AutoExpert#80]
The userscript! So handy, thank you. I figured the least I could do is give you some initial feedback with the hope that it will be useful to you. I didn't want to create separate issues for each of these since they're all pretty minor, so I'm just going to list them here to start. If you end up agreeing with any of them I can break out into separate issues if you'd like.

1. If I already have custom instructions, the buttons will overwrite them. Three possible solutions come to mind:
   - If either textarea contains content that does not match any of your instructions, display a warning the first time the user clicks a button warning them that their custom instructions will be overwritten and to manually save them if they want to keep them.
   - If either textarea contains content that does not match any of your instructions, add a new button that will restore their custom instructions
   - Add a warning to the userscript header, you have better things to do than this.

2. Some of your instructions require some user input. I saw `Address me as [name]. I'm a [age/gender] from [location]. My interests include [list of interests].` since it was up at the top. My next step would then be to read through all the prompts, which I do, every should do, but not everyone does. Some initial ideas:
     - A one-time notification about this when any button attached to instructions that need user input is clicked
     - Adding banner text in some manner that ideally gets their attention and instructs them to make the changes below and then delete the banner text. Ideally it would also put the instructions over the character limit so they can't just ignore it. 
     - Bah, a second note in the userscript header will suffice! 

3. After modifying the instructions, if I change to a different instruction and then back to the one I just modified, the changes are gone. Similar solutions here, too - save the changes when a different button is clicked, a one-time warning, note in the userscript header, etc.

4. I think if you rename the script whatever.user.js, the .user.js suffix will cause most userscript managers to recognize it and prompt to install it automatically. Which may or may not be something you want. 

5. Are you - yes you! - one of the 5.1k people who have starred this repo, happen to be reading through the issues AND have made it this far? You're probably already signed up to [Dustin's substack](https://spdustin.substack.com), but if not, do yourself the favor. Best in-depth, well-researched and original writing I've found. No gumroad traps or regurgitation of everyone else's work and daily links or any of that. But if all of that isnt enough, how about just doing it for me! What do I get out of it? Simple: the more people subbed, the more time he'll put towards writing more, which I will then read. Why should you care about me? Hey, you're the one still reading this when it's been obvious for a few sentences now it was drifting off into nonsense. You only have yourself to blame at this point. You're welcome in advance.

**Comment by spdustin** [comment]
Thanks again for the feedback. I've temporarily withdrawn it as I'm working on a debugger panel that will add be able to add modules for CI swapping, but it can still be found in the old commits. 😀
