### ISSUE TITLE
"This GPT is not supported on IOS"

### ISSUE THREAD

**Issue by RamboCambo** [spdustin/ChatGPT-AutoExpert#86]
### Edition
Check one or more:
- [x] Standard Edition
- [x] Developer Edition

Firstly, thank you spdustin for all your hard work! I love the bots and they make my life easier! Secondly, up the 12/11/2023, the new AutoExpert v6 GPT was working on the IOS version of the app. As of 13/11/2023, I now receive an error message saying this GPT is not supported on IOS and I cannot even continue with the previous conversations I had using the GPT on IOS. However, the Developer edition of v6 is supported on IOS. Has anything changed or is this an OpenAI?

**Comment by spdustin** [comment]
This should be working now; I removed a custom action that was preventing mobile use.
