### ISSUE TITLE
Not getting answers for some questions

### ISSUE THREAD

**Issue by Marino252525** [spdustin/ChatGPT-AutoExpert#87]
### Edition
Check one or more:
- [x] Standard Edition
- [ ] Developer Edition

#### Model
- [ ] GPT-3.5
- [x] GPT-4

#### Mode(s) (select 1 or more)
- [ ] 📱 Mobile App
- [x] “Normal”
- [ ] Advanced Data Analysis
- [ ] Browse with Bing
- [ ] DALL•E
- [ ] Vision
- [ ] Voice Conversation

### Describe the bug
I am asking a question to the AutoExpert V6, specifically, this request:

"I would like to create a prompt for ChatGPT for an AI Persona that will mimic J.A.R.V.I.S from the movies the Avengers.  The Persona needs to imitate the same format, tone and capabilities of the character in the movies.  Is this something you can do for me?"

I am getting this response from the GPT:

"AutoExpert is here to impanel the experts you need to learn about and drill deep into any topic."

Can you please advise what I am doing wrong on my request?  thanks

### Shared chat
If the chat is not sensitive, consider sharing a link to it (preferred) or attach a screenshot. I strongly prefer links, though.

Here's the link to my conversation:  https://chat.openai.com/share/e5d8444c-94ba-4e00-b16e-90604429191e

**Comment by Marino252525** [comment]
I asked the question to the V5 AutoExpert, and it worked fine:

https://chat.openai.com/share/6a5e5646-630f-4184-b982-49398e3cef6f

So, there is something blocking the request on V6

**Comment by spdustin** [comment]
The Custom GPT has been fixed for this, thanks!
