### ISSUE TITLE
Understanding Custom GPT Builder Prompt Behavior

### ISSUE THREAD

**Issue by hackiey** [spdustin/ChatGPT-AutoExpert#89]
Has anyone tried the prompt for Custom GPT Builder? I'm a bit confused about something:

When I'm creating a custom GPT in ChatGPT, the GPT Builder doesn't seem to interrupt and update the GPT behavior mid-conversation. Does this mean that the GPT Builder actually uses a function call? When I use this prompt myself, it produces the following contents:

> Great, we'll create a weather assistant GPT. Here's what we'll need to define:
The name of the GPT.
The detailed instructions on how it should respond to queries about weather.
A concise description of the GPT's behavior.
A welcome message that sets the tone for its interactions.
A set of example user prompts that will elicit responses showcasing its unique behavior as a weather assistant.
Please provide me with the name you would like for your weather assistant GPT, and any specific instructions or personality traits you want it to have. Once you've provided that information, I will proceed to call update_behavior with the appropriate settings and generate a profile picture.

or 

> Understood. You want a GPT named "Weather Assistant" that can provide weather updates for specific cities. I will now update the GPT's behavior with this new context.
namespace gizmo_editor {
update_behavior({
name: "Weather Assistant",
context: "You are a Weather Assistant designed to provide weather updates for specific cities. When asked about the weather in a particular city, you will give the current conditions, temperature, and possibly a short-term forecast, based on available data. You should always ensure that your information is clear, concise, and relevant to the user's request. If the city's name is not provided or is unclear, you should ask for clarification. Your responses should be friendly and professional, and you should not provide weather details for areas or topics not requested by the user.",
description: "I provide current weather updates for cities.",
welcome_message: "Hello! Ask me for a weather update.",
prompt_starters: ["What's the weather like in Paris today?", "Is it going to rain in Tokyo tomorrow?", "Can you give me the forecast for New York City?", "Do I need an umbrella in London right now?"],
})
} // namespace gizmo_editor
Now, let's generate a profile picture for "Weather Assistant."
namespace gizmo_editor {
generate_profile_pic({
prompt: "A simplistic representation of a sunny sky above a city skyline in the Nature-Inspired Style, using warm colors.",
})
} // namespace gizmo_editor

**Comment by spdustin** [comment]
That's not for general use; the system prompts are just there to show the "behind the scenes" prompts that different ChatGPT modes are using. 😃
