### ISSUE TITLE
Web Browsing and refuse to stay in character 

### ISSUE THREAD

**Issue by vaskosmihaylov** [spdustin/ChatGPT-AutoExpert#91]
### Edition
Check one or more:
- [x] Developer Edition

Hello,

Thank you for the contributions, for writing Custom GPTs @spdustin, and for your willingness to share.  I have several inquiries/issues with the AutoExpert (Dev) Custom GPT:

1. It seems that [AutoExpert (Dev)](https://chat.openai.com/g/g-pTF23RJ6f-autoexpert-dev) is not set to use Web Browsing. When I force it to browse the web I get :

```
📷AutoExpert (Dev)Error analyzing code:
search("web search string")
``` 

I know it could be related to the Chat GPT itself but I do not have problem with my custom GPTs

2. Most of the time the model does not stay in character nor change the specialists. For example, my first task is to write Python by using the JSON libary, and the model generates a proper plan, for example:

```
Language > Specialist: Python > Command Line Interface Implementation Specialist
Includes: argparse library, JSON formatting
Requirements: V=2 (simple), focus on integrating a new command line argument and formatting selected data in JSON

Plan
Review main.py to understand the current command-line argument structure.
Integrate a new command line argument, for instance, --minimal-output.
Modify the script to extract and format the required data (hostname, name, type) in JSON format when --minimal-output is used.
Test the integration with an example command.
```

however, if my next inquiry is related to something else let's say Ruby programming. The model does not change the specialist nor generate a new plan. I need to start a new chat for my new request. I assume the issue is connected somehow to the Custom Instructions ordering when the initial setup for the role was set, however, I cannot preview them.

**Comment by spdustin** [comment]
I'll check into this further; it should be switching experts for each request, but turbo is really weird about instructions... hang in there
