### ISSUE TITLE
Do OpenAI's new "GPT's" perform the same function as this project?

### ISSUE THREAD

**Issue by SeaDude** [spdustin/ChatGPT-AutoExpert#92]
Feels like you were weeks in front of OpenAI on this! Just built my first GPT and...it reminds me of this project. Are you considering building / have you already built your own GPT? 

The ingenious way that you handle "memory" (ctags now treesitter (i think)) is def a feature of this project.

**Comment by michaelskyba** [comment]
https://github.com/spdustin/ChatGPT-AutoExpert#%EF%B8%8F-new-%EF%B8%8F

**Comment by SeaDude** [comment]
Wow! I just went into my first GPT and added some forward slash commands...I can't believe how simple it was. Next level-type stuff...
