### ISSUE TITLE
links at the button of answer do not work

### ISSUE THREAD

**Issue by hoshython** [spdustin/ChatGPT-AutoExpert#99]
### Edition
Check one or more:
- [x] Standard Edition
- [ ] Developer Edition

#### Model
- [x] GPT-3.5
- [ ] GPT-4

#### Mode(s) (select 1 or more)
- [ ] 📱 Mobile App
- [x] “Normal”
- [ ] Advanced Data Analysis
- [x] Browse with Bing
- [ ] DALL•E
- [ ] Vision
- [ ] Voice Comveesation

### Describe the bug
urls in See also and You may also enjoy are not clickable

### To Reproduce
1. Go to 'chatgpt with any web browser'
2. Click on 'the links at the button of the answer'
4. See that there is a text cursor instead of a hand tool to click the link

### Expected behavior
It should click the link

### Shared chat
If the chat is not sensitive, consider sharing a link to it (preferred) or attach a screenshot. I strongly prefer links, though.

**Comment by wizzardx** [comment]
I've seen this too (on different browsers and devices). According to the browser dev tools, the working links are made like this:

```
<a target="_new" href="https://roadmap.sh/python">roadmap.sh for Python</a>
```

And none-working links are made like this:

```
<a target="_new">Python Learning Resources</a>
```

ie, href is not rendered in the html.

I've asked ChatGPT about it, and it says that it is generating the correct markup, eg like this:

```
[roadmap.sh for Python](https://roadmap.sh/python)
```

Or like this:

```
[Python Learning Resources](https://www.google.com/search?q=python+learning+resources)
```

But it's also claiming that the platform is for some reason not converting the markdown (for a google search) correctly into HTML, and recommends that I contact OpenAI's tech support, or to instead manually perform the Google searches.

**Comment by spdustin** [comment]
OpenAI have made changes to URL generation. These changes are enforced on the client-side, and remove the `href` attribute from hyperlinks. Sadly, there's not much I can do here. 🙁

I've updated the [AutoExpert (Chat) Custom GPT](https://chat.openai.com/g/g-LQHhJCXhW-autoexpert-chat) to add a warning when using the `/links` command.
